steps:
  - name: 'gcr.io/kaniko-project/executor:latest'
    args:
      - "--dockerfile=/workspace/Dockerfile"
      - "--context=dir:///workspace"
      - "--cache=true"
      - "--cache-ttl=360h"
      - "--destination=europe-west2-docker.pkg.dev/titled-jam-team/titled-jam-team/godot-ci"
options:
  pool:
    name: 'projects/titled-jam-team/locations/europe-west2/workerPools/kitty-workers'