steps:
  - name: 'ubuntu:focal'
    entrypoint: '/usr/bin/bash'
    args: [ "/workspace/build.sh" ]
artifacts:
  objects:
    location: 'gs://tjt-internal-builds/godot-ci/godot-3.5.server.x11.opt.tools.64.llvm'
options:
  pool:
    name: 'projects/titled-jam-team/locations/europe-west1/workerPools/kitty-workers-2'